from fpdf import FPDF
from datetime import datetime
import io

PLATFORM_NAME = 'GenQuantis Discovery Platform'

class PDFReport(FPDF):
    def __init__(self, generated_by: str = "GenQuantis Researcher"):
        super().__init__()
        self.generated_by = generated_by

    def header(self):
        self.set_font('Arial', 'B', 20)
        self.set_text_color(26, 35, 126)
        self.cell(0, 10, PLATFORM_NAME, 0, 1, 'C')
        self.set_font('Arial', 'I', 10)
        self.set_text_color(100)
        self.cell(0, 6, 'Advanced Molecular Analysis & Formulation Report', 0, 1, 'C')
        # Generated by line
        self.set_font('Arial', '', 9)
        self.set_text_color(80)
        self.cell(0, 6, f'Generated by: {self.generated_by}  |  {datetime.now().strftime("%Y-%m-%d %H:%M")}', 0, 1, 'C')
        self.ln(3)
        # Blue horizontal rule
        self.set_draw_color(26, 35, 126)
        self.set_line_width(1)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(8)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, 'Page ' + str(self.page_no()) + '/{nb}', 0, 0, 'C')
        self.cell(0, 10, 'GenQuantis Discovery Platform | Confidential', 0, 0, 'R')

def _get_name(user) -> str:
    """Safely extract display name from user object or string."""
    if user is None:
        return "GenQuantis Researcher"
    if isinstance(user, str):
        return user
    return getattr(user, 'full_name', None) or getattr(user, 'email', 'GenQuantis Researcher')

def generate_preformulation_pdf(data, user=None):
    pdf = PDFReport(generated_by=_get_name(user))
    pdf.alias_nb_pages()
    pdf.add_page()

    pdf.set_fill_color(232, 234, 246)
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, ' PREFORMULATION ANALYSIS REPORT', 0, 1, 'L', fill=True)
    pdf.ln(5)

    pdf.set_font('Arial', 'B', 12)
    pdf.cell(50, 8, 'Compound ID:', 0, 0)
    pdf.set_font('Arial', '', 12)
    pdf.cell(0, 8, str(data.get('compound_id')), 0, 1)

    pdf.set_font('Arial', 'B', 12)
    pdf.cell(50, 8, 'SMILES:', 0, 0)
    pdf.set_font('Arial', '', 10)
    
    # Insert spaces every 60 characters so FPDF can safely wrap the long unbroken string
    smiles_str = str(data.get('smiles', ''))
    wrapped_smiles = " ".join([smiles_str[i:i+60] for i in range(0, len(smiles_str), 60)])
    pdf.multi_cell(0, 8, wrapped_smiles)
    pdf.ln(5)

    pdf.set_fill_color(26, 35, 126)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, ' Physicochemical Properties', 0, 1, 'L', fill=True)
    pdf.set_text_color(0, 0, 0)
    pdf.set_font('Arial', '', 11)

    props = [
        ('Molecular Weight', f"{data.get('molecular_weight')} g/mol"),
        ('LogP', str(data.get('logp'))),
        ('TPSA', f"{data.get('tpsa')} A^2"),
        ('H-Bond Donors', str(data.get('h_bond_donors'))),
        ('H-Bond Acceptors', str(data.get('h_bond_acceptors'))),
        ('Rotatable Bonds', str(data.get('rotatable_bonds'))),
        ('Solubility Prediction', str(data.get('solubility_prediction'))),
    ]

    fill = False
    for label, value in props:
        pdf.set_fill_color(245, 245, 245)
        pdf.cell(60, 8, label, 1, 0, 'L', fill=fill)
        pdf.cell(130, 8, value, 1, 1, 'L', fill=fill)
        fill = not fill

    pdf.ln(10)

    pdf.set_fill_color(26, 35, 126)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, ' Drug Likeness Assessment', 0, 1, 'L', fill=True)
    pdf.set_text_color(0, 0, 0)

    status = data.get('drug_likeness_status')
    if status == 'Pass':
        pdf.set_text_color(46, 125, 50)
    else:
        pdf.set_text_color(198, 40, 40)

    pdf.set_font('Arial', 'B', 12)
    pdf.cell(60, 8, 'Status:', 0, 0)
    pdf.cell(0, 8, status, 0, 1)
    pdf.set_text_color(0, 0, 0)

    pdf.set_font('Arial', '', 11)
    pdf.cell(60, 8, 'Lipinski Violations:', 0, 0)
    pdf.cell(0, 8, str(data.get('lipinski_violations')), 0, 1)
    pdf.cell(60, 8, 'Veber Violations:', 0, 0)
    pdf.cell(0, 8, str(data.get('veber_violations')), 0, 1)

    pdf.ln(10)

    pdf.set_fill_color(26, 35, 126)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(190, 10, ' Potential Risks & Stability Assessment', 0, 1, 'L', fill=True)
    pdf.set_text_color(0, 0, 0)
    pdf.set_font('Arial', '', 11)

    pdf.set_x(10)
    risks = data.get('stability_risk', [])
    if not risks:
        pdf.cell(0, 8, 'No significant stability risks identified.', 0, 1)
    else:
        for risk in risks:
            pdf.set_x(10)
            pdf.multi_cell(0, 8, f"- {risk}")

    pdf.ln(5)
    pdf.set_font('Arial', 'B', 11)
    pdf.cell(0, 8, 'Recommended Excipients:', 0, 1)
    pdf.set_font('Arial', '', 11)
    excipients = data.get('recommended_excipients', [])
    pdf.cell(0, 8, ", ".join(excipients), 0, 1)

    return bytes(pdf.output(dest='S'))

def generate_formulation_pdf(form_data, pre_data, user=None):
    pdf = PDFReport(generated_by=_get_name(user))
    pdf.alias_nb_pages()
    pdf.add_page()

    pdf.set_fill_color(232, 234, 246)
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, ' FORMULATION STRATEGY REPORT', 0, 1, 'L', fill=True)
    pdf.ln(5)

    pdf.set_font('Arial', 'B', 12)
    pdf.cell(50, 8, 'Compound ID:', 0, 0)
    pdf.set_font('Arial', '', 12)
    pdf.cell(0, 8, str(form_data.get('compound_id')), 0, 1)

    pdf.set_font('Arial', 'B', 12)
    pdf.cell(50, 8, 'Molecular Weight:', 0, 0)
    pdf.set_font('Arial', '', 12)
    pdf.cell(0, 8, f"{pre_data.get('molecular_weight')} g/mol", 0, 1)
    pdf.ln(5)

    pdf.set_fill_color(26, 35, 126)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, ' Final Formulation Design', 0, 1, 'L', fill=True)
    pdf.set_text_color(0, 0, 0)
    pdf.set_font('Arial', '', 11)

    design_props = [
        ('Formulation Type', str(form_data.get('formulation_type'))),
        ('Drug Concentration', str(form_data.get('drug_concentration'))),
        ('Required Buffer', str(form_data.get('buffer'))),
        ('Stabilizer System', str(form_data.get('stabilizer'))),
        ('Surfactant', str(form_data.get('surfactant'))),
        ('Recommended pH', str(form_data.get('recommended_ph'))),
    ]

    fill = False
    for label, value in design_props:
        pdf.set_fill_color(245, 245, 245)
        pdf.cell(65, 10, label, 1, 0, 'L', fill=fill)
        pdf.cell(125, 10, value, 1, 1, 'L', fill=fill)
        fill = not fill

    pdf.ln(10)

    pdf.set_fill_color(26, 35, 126)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, ' Scientific Rationale & Refinement Notes', 0, 1, 'L', fill=True)
    pdf.set_text_color(0, 0, 0)
    pdf.set_font('Arial', '', 11)

    rationale = []
    solubility = pre_data.get('solubility_prediction')
    if solubility in ['Low', 'Very Low']:
        rationale.append(f"Due to {solubility} solubility, a surfactant ({form_data.get('surfactant')}) is included to ensure proper dissolution.")

    risks = pre_data.get('stability_risk', [])
    if any("hygroscopicity" in r for r in risks):
        rationale.append("High hygroscopicity risk detected; Sucrose is used as a stabilizer over Trehalose.")
    else:
        rationale.append("Stability risks are manageable; Trehalose is used for cryoprotection/stabilization.")

    for r in rationale:
        pdf.set_x(10)
        pdf.multi_cell(0, 8, f"- {r}")

    pdf.ln(5)
    pdf.set_font('Arial', 'I', 10)
    pdf.multi_cell(0, 8, "Note: This formulation design is AI-generated based on predicted molecular properties. Physical stability testing and compatibility studies (DSC, TGA, HPLC) are recommended for final validation.")

    return bytes(pdf.output(dest='S'))

def generate_screening_pdf(job_data, user=None):
    pdf = PDFReport(generated_by=_get_name(user))
    pdf.alias_nb_pages()
    pdf.add_page()

    pdf.set_fill_color(232, 234, 246)
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, ' HIGH-THROUGHPUT HIT SCREENING REPORT', 0, 1, 'L', fill=True)
    pdf.ln(5)

    pdf.set_font('Arial', 'B', 12)
    pdf.cell(50, 8, 'Target ID:', 0, 0)
    pdf.set_font('Arial', '', 12)
    pdf.cell(0, 8, str(job_data.get('target_id')), 0, 1)

    pdf.set_font('Arial', 'B', 12)
    pdf.cell(50, 8, 'Library ID:', 0, 0)
    pdf.set_font('Arial', '', 12)
    pdf.cell(0, 8, str(job_data.get('library_id')), 0, 1)

    pdf.set_font('Arial', 'B', 12)
    pdf.cell(50, 8, 'AI Model:', 0, 0)
    pdf.set_font('Arial', '', 12)
    pdf.cell(0, 8, str(job_data.get('results', {}).get('model_used', 'XGBoost-v1')), 0, 1)
    pdf.ln(10)

    pdf.set_fill_color(26, 35, 126)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, ' Screening Results Summary', 0, 1, 'L', fill=True)
    pdf.set_text_color(0, 0, 0)

    hits = job_data.get('results', {}).get('top_hits', [])
    pdf.set_font('Arial', '', 11)
    pdf.cell(0, 10, f"Total Compounds Screened: {job_data.get('results', {}).get('hits_found', 0)}", 0, 1)
    pdf.cell(0, 10, f"Identified Hits (Top {len(hits)}):", 0, 1)
    pdf.ln(5)

    pdf.set_fill_color(245, 245, 245)
    pdf.set_font('Arial', 'B', 10)
    pdf.cell(15, 10, 'Rank', 1, 0, 'C', fill=True)
    pdf.cell(45, 10, 'Compound ID', 1, 0, 'C', fill=True)
    pdf.cell(100, 10, 'SMILES (Truncated)', 1, 0, 'C', fill=True)
    pdf.cell(30, 10, 'pIC50', 1, 1, 'C', fill=True)

    pdf.set_font('Arial', '', 9)
    for i, hit in enumerate(hits):
        rank = str(i + 1)
        comp_id = str(hit.get('molecule_id', f"CMP_{i}"))[:15]
        smiles = str(hit.get('smiles', ''))[:50] + "..."
        score = str(hit.get('affinity', '0.0'))

        pdf.cell(15, 8, rank, 1, 0, 'C')
        pdf.cell(45, 8, comp_id, 1, 0, 'C')
        pdf.cell(100, 8, smiles, 1, 0, 'L')
        pdf.cell(30, 8, score, 1, 1, 'C')

        if i >= 40:
            break

    pdf.ln(10)
    pdf.set_font('Arial', 'I', 9)
    pdf.multi_cell(0, 6, "Report Note: Binding affinity scores (pIC50) are predicted using a 2,400-parameter XGBoost classifier. Scores > 7.0 indicate high potency candidates. Structural validation via molecular docking is recommended for top-ranked hits.")

    return bytes(pdf.output(dest='S'))

def generate_target_report(target_data, user=None):
    pdf = PDFReport(generated_by=_get_name(user))
    pdf.alias_nb_pages()
    pdf.add_page()

    pdf.set_fill_color(232, 234, 246)
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, ' THERAPEUTIC TARGET DISCOVERY REPORT', 0, 1, 'L', fill=True)
    pdf.ln(5)

    pdf.set_font('Arial', 'B', 12)
    pdf.cell(50, 8, 'Target Name:', 0, 0)
    pdf.set_font('Arial', '', 12)
    pdf.cell(0, 8, str(target_data.get('name')), 0, 1)

    pdf.set_font('Arial', 'B', 12)
    pdf.cell(50, 8, 'UniProt ID:', 0, 0)
    pdf.set_font('Arial', '', 12)
    pdf.cell(0, 8, str(target_data.get('uniprot_id', 'N/A')), 0, 1)

    pdf.set_font('Arial', 'B', 12)
    pdf.cell(50, 8, 'PDB Structures:', 0, 0)
    pdf.set_font('Arial', '', 12)
    pdf.cell(0, 8, ", ".join(target_data.get('pdb_ids', [])), 0, 1)

    pdf.set_font('Arial', 'B', 12)
    pdf.cell(50, 8, 'Source:', 0, 0)
    pdf.set_font('Arial', '', 12)
    source = "RCSB PDB (Crystal)" if target_data.get('pdb_ids') else "AlphaFold (Predicted)"
    pdf.cell(0, 8, source, 0, 1)
    pdf.ln(5)

    pdf.set_fill_color(26, 35, 126)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, ' Genomic Sequence Analysis', 0, 1, 'L', fill=True)
    pdf.set_text_color(0, 0, 0)
    pdf.set_font('Courier', '', 9)
    seq = str(target_data.get('sequence', 'No sequence data available.'))
    pdf.multi_cell(0, 5, seq)
    pdf.ln(10)

    pdf.set_fill_color(26, 35, 126)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, ' PPI Interactome Mapping (STRING)', 0, 1, 'L', fill=True)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(5)

    partners = target_data.get('interaction_partners', [])
    if partners:
        pdf.set_fill_color(245, 245, 245)
        pdf.set_font('Arial', 'B', 10)
        pdf.cell(40, 8, 'Partner', 1, 0, 'C', fill=True)
        pdf.cell(50, 8, 'Method', 1, 0, 'C', fill=True)
        pdf.cell(60, 8, 'Interaction Type', 1, 0, 'C', fill=True)
        pdf.cell(40, 8, 'String Score', 1, 1, 'C', fill=True)
        pdf.set_font('Arial', '', 10)
        for p in partners:
            pdf.cell(40, 8, str(p.get('symbol')), 1, 0, 'C')
            pdf.cell(50, 8, str(p.get('method')), 1, 0, 'C')
            pdf.cell(60, 8, str(p.get('type')), 1, 0, 'C')
            pdf.cell(40, 8, f"{float(p.get('score', 0))*100:.0f}%", 1, 1, 'C')
    else:
        pdf.cell(0, 8, 'No protein interaction data available.', 0, 1)

    pdf.ln(10)

    pdf.set_fill_color(26, 35, 126)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, ' Identified ChEMBL Binders (Top 15)', 0, 1, 'L', fill=True)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(5)

    ligands = target_data.get('known_ligands', [])
    if ligands:
        pdf.set_fill_color(245, 245, 245)
        pdf.set_font('Arial', 'B', 10)
        pdf.cell(40, 8, 'ChEMBL ID', 1, 0, 'C', fill=True)
        pdf.cell(30, 8, 'Metric', 1, 0, 'C', fill=True)
        pdf.cell(30, 8, 'Value', 1, 0, 'C', fill=True)
        pdf.cell(90, 8, 'SMILES Signature', 1, 1, 'C', fill=True)
        pdf.set_font('Arial', '', 8)
        for i, l in enumerate(ligands[:15]):
            pdf.cell(40, 8, str(l.get('molecule_chembl_id')), 1, 0, 'C')
            pdf.cell(30, 8, str(l.get('standard_type')), 1, 0, 'C')
            pdf.cell(30, 8, f"{l.get('standard_value')} {l.get('standard_units')}", 1, 0, 'C')
            pdf.cell(90, 8, str(l.get('smiles'))[:55] + "...", 1, 1, 'L')
    else:
        pdf.cell(0, 8, 'No bioactivity data found in ChEMBL.', 0, 1)

    pdf.ln(10)
    pdf.set_font('Arial', 'I', 9)
    pdf.multi_cell(0, 6, "Platform Disclaimer: This report is generated by GenQuantis Discovery AI. Structural and bioactivity data is retrieved from external repositories (RCSB, UniProt, ChEMBL, STRING). Experimental validation is required for target tractability.")

    return bytes(pdf.output(dest='S'))

def generate_optimization_pdf(job_data: dict, user=None):
    """Generate a PDF report for a Lead Optimization job."""
    pdf = PDFReport(generated_by=_get_name(user))
    pdf.alias_nb_pages()
    pdf.add_page()

    pdf.set_fill_color(232, 234, 246)
    pdf.set_font('Arial', 'B', 14)
    pdf.cell(0, 10, ' LEAD OPTIMIZATION REPORT', 0, 1, 'L', fill=True)
    pdf.ln(5)

    results = job_data.get('results') or {}

    pdf.set_font('Arial', 'B', 12)
    pdf.cell(60, 8, 'Target ID:', 0, 0)
    pdf.set_font('Arial', '', 12)
    pdf.cell(0, 8, str(job_data.get('target_id', 'N/A')), 0, 1)

    pdf.set_font('Arial', 'B', 12)
    pdf.cell(60, 8, 'AI Strategy:', 0, 0)
    pdf.set_font('Arial', '', 12)
    pdf.cell(0, 8, str(results.get('model_used', 'N/A')), 0, 1)

    pdf.set_font('Arial', 'B', 12)
    pdf.cell(60, 8, 'Status:', 0, 0)
    pdf.set_font('Arial', '', 12)
    pdf.cell(0, 8, str(job_data.get('status', 'N/A')), 0, 1)
    pdf.ln(5)

    pdf.set_fill_color(26, 35, 126)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('Arial', 'B', 12)
    pdf.cell(0, 10, ' Potency Optimization Results', 0, 1, 'L', fill=True)
    pdf.set_text_color(0, 0, 0)
    pdf.set_font('Arial', '', 11)

    affinity_rows = [
        ('Original pIC50', str(results.get('original_affinity', 'N/A'))),
        ('Optimized pIC50', str(results.get('optimized_affinity', 'N/A'))),
        ('Potency Improvement', str(results.get('improvement', 'N/A'))),
        ('Optimized SMILES', str(results.get('optimized_smiles', 'N/A'))[:60] + '...'),
    ]

    fill = False
    for label, value in affinity_rows:
        pdf.set_fill_color(245, 245, 245)
        pdf.cell(65, 8, label, 1, 0, 'L', fill=fill)
        pdf.cell(125, 8, value, 1, 1, 'L', fill=fill)
        fill = not fill

    pdf.ln(10)

    sar = results.get('sar_analysis', [])
    if sar:
        pdf.set_fill_color(26, 35, 126)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font('Arial', 'B', 12)
        pdf.cell(0, 10, ' Structure-Activity Relationship (SAR) Analysis', 0, 1, 'L', fill=True)
        pdf.set_text_color(0, 0, 0)
        pdf.ln(3)
        pdf.set_fill_color(245, 245, 245)
        pdf.set_font('Arial', 'B', 10)
        pdf.cell(100, 9, 'Mutation / Modification', 1, 0, 'C', fill=True)
        pdf.cell(45, 9, 'Delta Affinity', 1, 0, 'C', fill=True)
        pdf.cell(45, 9, 'Impact', 1, 1, 'C', fill=True)
        pdf.set_font('Arial', '', 10)
        for item in sar:
            delta = item.get('affinity_change', 0)
            pdf.cell(100, 8, str(item.get('mutation', '')), 1, 0, 'L')
            pdf.cell(45, 8, f"+{delta}" if delta > 0 else str(delta), 1, 0, 'C')
            pdf.cell(45, 8, str(item.get('impact', '')), 1, 1, 'C')

    pdf.ln(10)
    pdf.set_font('Arial', 'I', 9)
    pdf.multi_cell(0, 6, "Report Note: Lead optimization scores are predicted using an XGBoost-based binding affinity model combined with evolutionary/generative AI strategies. Experimental SPR/ITC validation is required before advancing to clinical candidate selection.")

    return bytes(pdf.output(dest='S'))
